In [ ]:
print("Hello, Google Colab!")

Hello, Google Colab!


# This is an example for Markdown cells
### LaTeX example

$$\int_0^x x^2 dx = \frac{x^3}{3}$$

Anaconda web page (https://www.anaconda.com/)

|Name | Year |
|:---:| :--- |
|Python|1991|
|C|1972|
|Fortran|1954|

In [ ]:
import numpy as np

arr=np.array([1,2,3.3,5.5])

x = arr.astype(int)
y = arr.astype(float)
z = arr.astype(complex)
print(x, y, z)

[1 2 3 5] [1.  2.  3.3 5.5] [1. +0.j 2. +0.j 3.3+0.j 5.5+0.j]


In [ ]:
a = np.array([0,1,2,3])
b = a
a[1]=100
print(b)
a is b

[  0 100   2   3]


True

In [ ]:
a = np.array([0,1,2,3])
b = a.copy()
print(a==b)
print(a is b)
a[1]=100
print(a)
print(b)

[ True  True  True  True]
False
[  0 100   2   3]
[0 1 2 3]


In [ ]:
for i in range(10):
  x = 2*i
  print(i,x)

for i in range(10): print(i)

0 0
1 2
2 4
3 6
4 8
5 10
6 12
7 14
8 16
9 18
0
1
2
3
4
5
6
7
8
9


In [ ]:
b, c= 5, -1
for a in np.arange(1, 11):
  x = (-b + np.sqrt(b**2-4*a*c))/(2*a)
  print(f'a={a:2d}  sol={x:.3f}')

# ax^2 + 5x - 1 = 0 푸는거
# f는 정형화된 출력 f가 없으면 따옴표 내부가 전부 문자열로 간주됨

a= 1  sol=0.193
a= 2  sol=0.186
a= 3  sol=0.180
a= 4  sol=0.175
a= 5  sol=0.171
a= 6  sol=0.167
a= 7  sol=0.163
a= 8  sol=0.159
a= 9  sol=0.156
a=10  sol=0.153


In [ ]:
b, c= 5, -1
for a in np.arange(1, 11):
  x = (-b + np.sqrt(b**2-4*a*c))/(2*a)
print(f'a={a:2d}  sol={x:.3f}')

# 들여쓰기의 중요성

a=10  sol=0.153


In [ ]:
n = 0
while n<10:
  print(n)
  n=n+3

0
3
6
9


In [ ]:
a, b, c = 1, 1, -1
while b**2-4*a*c>0:
  xp = (-b+np.sqrt(b**2-4*a*c))/(2*a)
  xm = (-b-np.sqrt(b**2-4*a*c))/(2*a)
  print(f'c={c:.3f}, x={xp:.3f},   {xm:.3f}')
  c += 0.1

c=-1.000, x=0.618,   -1.618
c=-0.900, x=0.572,   -1.572
c=-0.800, x=0.525,   -1.525
c=-0.700, x=0.475,   -1.475
c=-0.600, x=0.422,   -1.422
c=-0.500, x=0.366,   -1.366
c=-0.400, x=0.306,   -1.306
c=-0.300, x=0.242,   -1.242
c=-0.200, x=0.171,   -1.171
c=-0.100, x=0.092,   -1.092
c=-0.000, x=0.000,   -1.000
c=0.100, x=-0.113,   -0.887
c=0.200, x=-0.276,   -0.724


In [ ]:
a=0
for i in range(20):
  if i>=5:
    a += i
print(a)

180


In [ ]:
sum0, sum1, sum2 = 0, 0, 0
for i in range(10):
  if (i%2==0) and (i%3 ==0):
    sum0 += i
  elif (i%2==1) or (i%3 ==0):
    sum1 += i
  else:
    sum2 += i

print(sum0,sum1,sum2)

6 25 14


In [24]:
n = 0
while True:
  n+=1
  if n==20:
    break
  print(n)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
